Updated images for iMovo subs card launch
guardian/support-frontend pull request #2753
Opened 2020-10-05 16:06 UTC by i-hardy

## Why are you doing this?

Adding the updated images for both the subscription card and home delivery tabs on the Print Subscriptions landing page, behind the existing `useDigitalVoucher` switch

[**Trello Card**](https://trello.com/c/cb6a4ZM1)

## Changes

* Adding new images
* Adjustments to styling to accommodate the new images in accordance with the designs

## Did you enjoy your PR experience?

 - [ ] [PR experience rated](https://forms.gle/N6FsTGG8JQFGV4Ha9)

## Screenshots

(images are not shown below desktop breakpoint)

![Screenshot 2020-10-05 at 16 38 47](https://user-images.githubusercontent.com/29146931/95100943-8b79c900-0729-11eb-920e-eb997fe2a740.png)
![Screenshot 2020-10-05 at 16 38 57](https://user-images.githubusercontent.com/29146931/95100957-8f0d5000-0729-11eb-8ac5-5a96c3d7a512.png)

2020-10-06 09:12 UTC, rupertbates commented on support-frontend/assets/helpers/theGrid.js
> +  printCampaigniMovo: '3cca8e05f3253f5a14329429ec3f6f139f84929a/0_21_562_337',
I think `printCampaignDigitalVoucher` would be a better name, we don't generally use iMovo in code I don't think

2020-10-06 09:13 UTC, rupertbates commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
I would revert this as nothing has actually changed

2020-10-06 09:14 UTC, rupertbates approved these changes
A couple of suggestions but nothing serious 👍

2020-10-06 09:29 UTC, lucymonie requested changes
Forgive me if my information is out of date, but I think the images for the order summary in the checkout are also meant to be updated in this PR.

2020-10-06 09:29 UTC, lucymonie commented on support-frontend/assets/pages/paper-subscription-landing/components/content/deliveryTab.jsx
> +      gridId={useDigitalVoucher ? 'printCampaignHDiMovo' : 'printCampaignHD'}
I think this is getting updated and isn't conditional on useDigitalVoucher (could be misunderstanding though!)

2020-10-07 15:57 UTC, lucymonie approved these changes

2020-10-07 16:01 UTC, merged