Add new Digital Sub gift purchase fields into the checkout
guardian/support-frontend pull request #2769
Opened 2020-10-13 13:48 UTC by rupertbates

## Why are you doing this?

[**Trello Card**](https://trello.com)

## Changes

* Change 1
* Change 2

## Did you enjoy your PR experience?

 - [ ] [PR experience rated](https://forms.gle/N6FsTGG8JQFGV4Ha9)

## Accessibility test checklist
 - [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
 - [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
 - [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

## Screenshots

2020-10-13 14:34 UTC, lucymonie approved these changes
I got nervous about these changes because of the browser issues we had with dates. So I went on your branch and ran the code in FireFox so I can affirm that it's all good!

~🍰 ~

Sadly I have to cross out the cake as something is now broken with the form-level errors. The `checkGiftStartDate` function uses the giftDeliveryDate to determine if there should be an error on submission of the form.

2020-10-13 14:45 UTC, lucymonie requested changes
However, something is now broken with the form-level errors. The checkGiftStartDate function uses the giftDeliveryDate to determine if there should be an error on submission of the form.

2020-10-13 15:05 UTC, rupertbates commented
> However, something is now broken with the form-level errors. The checkGiftStartDate function uses the giftDeliveryDate to determine if there should be an error on submission of the form.

Thanks for spotting this, should be fixed now

2020-10-14 12:31 UTC, johnduffell approved these changes

2020-10-15 10:36 UTC, lucymonie approved these changes

2020-10-15 10:47 UTC, merged