Disable focus manager on subscription checkout
guardian/support-frontend pull request #2909
Opened 2021-01-08 11:57 UTC by SiAdcock

## What are you doing in this PR?

- Disable Source's Focus Manager on subscription checkout page

[**Trello Card**](https://trello.com)

## Why are you doing this?

The Focus Manager adds a blue "halo" around interactive components. This is intended for when users tab into, for instance, a text input field. However, by default clicking on an interactive element also triggers the focus state, applying focus styles inappropriately.

By running `FocusStyleManager.onlyShowFocusOnTabs()`, we can ensure the focus state only applies when the user presses the tab key, not when they click on the element.

A similar change was made to the contributions landing page in #2384

## Accessibility test checklist
 - [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
 - [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
 - [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

## Screenshots

![2021-01-08 11 55 24](https://user-images.githubusercontent.com/5931528/104012852-712c0d00-51a8-11eb-9919-fcf1084b2016.gif)

2021-01-12 12:12 UTC, i-hardy requested changes
This looks great, working perfectly for me locally. Would you mind adding the same thing to our two other checkouts- `pages/paper-subscription-checkout/paperSubscriptionCheckout.jsx` and `pages/weekly-subscription-checkout/weeklySubscriptionCheckout.jsx`?

2021-01-14 09:40 UTC, SiAdcock commented
Thanks @i-hardy, I have implemented the change on those additional pages. Please could you take another look and let me know if there's anything else I can do?

Thanks for the local testing 🙏

2021-01-14 10:35 UTC, i-hardy approved these changes

2021-01-14 10:36 UTC, i-hardy commented
All looks great, thank you @SiAdcock!

2021-01-14 10:43 UTC, SiAdcock commented
Thanks so much @i-hardy!

Am I safe to merge, or shall I leave it in your capable hands? 🙌

2021-01-14 14:14 UTC, merged