Quantum Metric: sendEventContributionCartValue
guardian/support-frontend pull request #4204
Opened 2022-09-08 14:32 UTC by GHaberis

## What are you doing in this PR?

We currently have a function `sendEventContributionAmountUpdated` that's called when user clicks on a contribution amount button on the contributions checkout, this function informs Quantum Metric of the "cart value" of the user on the checkout. 

We currently only send this event when a user clicks a payment amount button. However a users cart value can be set on other page events, specifically

- **Page load:** When a user lands on the page there is a default payment frequency and a default payment amount already selected - so the cart essentially has a default value on page load, should we track this as a user could feasibly checkout without clicking a payment amount button.

- **Changing payment frequency:** When a user switches between single/monthly/annual the selected payment amount changes they are effectively altering their cart value as the default selected amount changes too. 

We're not informing Quantum Metric of the cart value on these events. This PR addresses that by 1) Renaming `sendEventContributionAmountUpdated` to `sendEventContributionCartValue` to more accurately reflect this functions actual purpose and 2) Calling `sendEventContributionCartValue` on page load by hooking into the side effects `setAllAmounts` and `setProductType` actions and on changing payment frequency by hooking into the side effect for the`setProductType` action. When these actions are executed we now call `sendEventContributionCartValue`.

## Screenshots

2022-09-09 10:38 UTC, GHaberis commented on support-frontend/assets/helpers/tracking/quantumMetric.ts
> +	).catch(() => {
This was logging "undefined" as e.message and the error it gets upon inspection isn't helpful so I'm removing it.

2022-09-12 17:02 UTC, i-hardy requested changes

2022-09-22 16:23 UTC, GHaberis commented on support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
> +		.productType as ContributionType;
Just looking into this, this function `getContributionCartValueData` is called in once place, from a side effect within this module, that side effect passes `listenerApi.getState().page` as the argument, which has the type `PageState`. If I change the signature of `getContributionCartValueData` to accept a parameter of type `ContributionsState` I'll get a type error. Is there anyway I can get the `ContributionsState` from the `listenerApi`?

2022-10-05 09:38 UTC, GHaberis commented on support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
> +		.productType as ContributionType;
I've made the suggested change by replacing `listenerApi.getState().page` with `listenerApi.getState()`.

2022-10-05 09:44 UTC, GHaberis commented on support-frontend/assets/helpers/redux/checkout/product/contributionsSideEffects.ts
> +}
Done!

2022-10-05 09:44 UTC, GHaberis commented
@i-hardy thanks for your review, I've made the changes suggested.

2022-10-06 09:20 UTC, i-hardy approved these changes
Looks good 👍

2022-10-10 15:03 UTC, merged