Stop Search engine's indexing promo T&Cs pages on support site
guardian/support-frontend pull request #5598
Opened 2024-01-10 16:38 UTC by GHaberis

## What are you doing in this PR?

In the Google Search Console we can see users are landing on pages used for displaying Promo offer T&Cs, for example…

https://support.theguardian.com/p/10ANNUAL/terms
https://support.theguardian.com/p/ANNUAL-INTRO-US/terms

These pages are auto generated at the p/*/terms route using promo codes set-up in the promo code tool. They’re consistently in the top 10 pages accessed via Google search.

These pages at the p/*/terms route should not be indexed by Search engines.

[**Trello Card**](https://trello.com/c/yAmcQBuG/462-stop-google-indexing-promo-tcs-pages-on-support-site)

2024-01-11 09:10 UTC, jamesgorrie requested changes
Just a note on how `Option`s are used.

2024-01-11 09:25 UTC, GHaberis commented on support-frontend/app/controllers/Promotions.scala
> +          Some(true),
Ah ok thanks for the suggestion, named arguments is way better for readability, I suspected this could've been improved!

2024-01-11 09:26 UTC, GHaberis commented on support-frontend/app/views/main.scala.html
> +  noindex: Option[Boolean] = None,
Yeah it didn't show an error in VSCode and compiled ok so I didn't see this.

2024-01-12 10:36 UTC, rBangay approved these changes

2024-01-15 11:38 UTC, jamesgorrie approved these changes

2024-01-15 11:46 UTC, merged